In [17]:
# Dependencies
from matplotlib import pyplot as plt
import numpy
import pandas as pd
import statistics

In [18]:
# Read CSV
city_data = "city_data.csv"
city_data_df = pd.read_csv(city_data)

city_data_df

                     city  driver_count      type
0              Kelseyland            63     Urban
1              Nguyenbury             8     Urban
2            East Douglas            12     Urban
3           West Dawnfurt            34     Urban
4          Rodriguezburgh            52     Urban
5       South Josephville             4     Urban
6        West Sydneyhaven            70     Urban
7             Travisville            37     Urban
8             Torresshire            70     Urban
9               Lisaville            66     Urban
10              Mooreview            34     Urban
11             Smithhaven            67     Urban
12            Carrollfort            55     Urban
13        Port Josephfurt            28     Urban
14       Lake Jeffreyland            15     Urban
15            South Louis            12     Urban
16             West Peter            61     Urban
17        Kimberlychester            13     Urban
18             Alyssaberg            67     Urban
19               Sarabury            46     Urban
20            Yolandafurt             7     Urban
21            Edwardsbury            11     Urban
22        New Andreamouth            42     Urban
23              New David            31     Urban
24             Arnoldview            41     Urban
25           Williamshire            70     Urban
26               Lisatown            47     Urban
27              New Aaron            60     Urban
28            Swansonbury            64     Urban
29             Fosterside            69     Urban
..                    ...           ...       ...
96               New Lynn            20  Suburban
97              Port Jose            11  Suburban
98               Johnland            13  Suburban
99              West Tony            17  Suburban
100            Port James             3  Suburban
101          Campbellport            26  Suburban
102          Port Guytown            26  Suburban
103           Webstertown            26  Suburban
104             Clarkstad            21  Suburban
105       North Tracyfort            18  Suburban
106           Martinmouth             5  Suburban
107      New Jessicamouth            22  Suburban
108  South Elizabethmouth             3     Rural
109         East Troybury             3     Rural
110             Kinghaven             3     Rural
111          New Johnbury             6     Rural
112              Erikport             3     Rural
113           Jacksonfort             6     Rural
114           Shelbyhaven             9     Rural
115           Matthewside             4     Rural
116          Kennethburgh             3     Rural
117          South Joseph             3     Rural
118         Manuelchester             7     Rural
119           Stevensport             6     Rural
120         North Whitney            10     Rural
121          East Stephen             6     Rural
122           East Leslie             9     Rural
123        Hernandezshire            10     Rural
124             Horneland             8     Rural
125        West Kevintown             5     Rural

[126 rows x 3 columns]

In [19]:
ride_data = "ride_data.csv"
ride_data_df = pd.read_csv(ride_data)

ride_data_df

                      city                 date   fare        ride_id
0                 Sarabury  2016-01-16 13:49:27  38.35  5403689035038
1                South Roy  2016-01-02 18:42:34  17.49  4036272335942
2              Wiseborough  2016-01-21 17:35:29  44.18  3645042422587
3              Spencertown  2016-07-31 14:53:22   6.87  2242596575892
4               Nguyenbury  2016-07-09 04:42:44   6.28  1543057793673
5              New Jeffrey  2016-02-22 18:36:25  36.01  9757888452346
6            Port Johnstad  2016-06-07 02:39:58  17.15  4352278259335
7                Jacobfort  2016-09-20 20:58:37  22.98  1500221409082
8              Travisville  2016-01-15 17:32:02  27.39   850152768361
9               Sandymouth  2016-11-16 07:27:00  21.61  2389035050524
10         New Andreamouth  2016-04-11 07:20:48   7.72  9992929847990
11           New Christine  2016-09-13 15:06:42  24.89  7918411468537
12             Stewartview  2016-03-29 05:15:56  23.88  6778235889588
13          Rodriguezburgh  2016-09-05 05:20:39   4.54  9650770953139
14        West Sydneyhaven  2016-08-02 21:18:44  12.87  7994760397230
15             Swansonbury  2016-07-11 18:42:11  39.30   744481862626
16                Lisatown  2016-07-05 18:09:14   5.82  6370359473201
17               East Erin  2016-11-03 01:03:05   7.51  4744239092530
18         Port Martinberg  2016-01-06 17:11:30   8.66  7298562820881
19             Wiseborough  2016-09-12 18:43:41  26.83  9304728540000
20             Edwardsbury  2016-02-27 03:55:54  20.17  8514523868075
21               Jacobfort  2016-06-12 17:01:29  34.47  4135673527977
22             Pamelahaven  2016-03-26 12:56:57  36.43  3015329826849
23              Fosterside  2016-08-12 11:52:41  28.08   133077693483
24               Jacobfort  2016-09-17 12:38:58  38.25  2182376146051
25        West Sydneyhaven  2016-08-23 14:49:59  36.12  5885997568611
26             West Alexis  2016-01-16 00:33:02  26.62  1574788996743
27             Carrollfort  2016-06-24 20:11:11   6.45  1092683495142
28               New David  2016-01-12 20:48:43  38.68  5229089333754
29             Stewartview  2016-10-15 05:26:40  11.74  8402784599831
...                    ...                  ...    ...            ...
2345        West Kevintown  2016-06-15 19:53:16  13.50  9577921579881
2346           Matthewside  2016-02-23 00:43:51  40.84  8665248512368
2347              Erikport  2016-11-26 04:39:52  44.21  9598643212986
2348             Kinghaven  2016-07-23 08:23:50  46.08  8440329717166
2349        Hernandezshire  2016-02-24 17:30:44  44.68  6389115653382
2350          Kennethburgh  2016-01-01 04:31:43  33.53  5149088250183
2351           Stevensport  2016-02-22 02:45:07  19.91   808097865942
2352  South Elizabethmouth  2016-11-23 07:47:18  46.39  1939838068038
2353          East Stephen  2016-07-30 21:25:01  35.39  1107870956099
2354           Jacksonfort  2016-10-01 13:41:00  34.17  7750597960630
2355          Kennethburgh  2016-04-30 20:44:27  23.58  4524301143267
2356             Horneland  2016-03-25 02:05:42  20.04  5729327140644
2357           Shelbyhaven  2016-01-25 01:39:16  59.43  8088329954312
2358              Erikport  2016-08-03 21:19:11  47.67  9201708664049
2359          Kennethburgh  2016-11-19 06:59:31  18.37  5897895798960
2360           Jacksonfort  2016-10-20 16:42:54  37.75  4356781814784
2361          South Joseph  2016-10-15 03:53:06  32.50  2758038144583
2362           Matthewside  2016-05-18 02:00:30  48.67  2049161404256
2363           Matthewside  2016-08-08 14:02:35  24.97  2872494724827
2364          South Joseph  2016-10-28 09:52:15  25.34  6706101910500
2365  South Elizabethmouth  2016-07-19 09:35:59  31.09  2959749591417
2366         North Whitney  2016-11-11 16:24:16  22.99  3454326063039
2367          New Johnbury  2016-08-29 02:36:06  18.83  7368222134792
2368           East Leslie  2016-06-22 07:45:30  34.54   684950063164
2369          Kennethburgh  2016-06-07 11:43:43  56.02   311733202150
2370        West Kevintown  2016-02-10 00:50:04  34.69  9595491362610
2371         East Troybury  2016-03-14 01:55:32  38.80  9205811495606
2372         North Whitney  2016-01-26 01:06:41  34.92  4165974278063
2373          South Joseph  2016-09-28 07:30:55  12.55  4336212615821
2374  South Elizabethmouth  2016-04-21 10:20:09  16.50  5702608059064

[2375 rows x 4 columns]

In [20]:
combined_city_df = pd.merge(city_data_df,ride_data_df, how='outer', on='city')
combined_city_df

,city,driver_count,type,date,fare,ride_id
0,Kelseyland,63,Urban,2016-08-19 04:27:52,5.51,6246006544795
1,Kelseyland,63,Urban,2016-04-17 06:59:50,5.54,7466473222333
2,Kelseyland,63,Urban,2016-05-04 15:06:07,30.54,2140501382736
3,Kelseyland,63,Urban,2016-01-25 20:44:56,12.08,1896987891309
4,Kelseyland,63,Urban,2016-08-09 18:19:47,17.91,8784212854829
5,Kelseyland,63,Urban,2016-10-24 15:15:46,33.56,4797969661996
6,Kelseyland,63,Urban,2016-06-06 13:54:23,20.81,9811478565448
7,Kelseyland,63,Urban,2016-08-10 07:02:40,44.53,1563171128434
8,Kelseyland,63,Urban,2016-07-05 17:37:13,29.02,6897992353955
9,Kelseyland,63,Urban,2016-04-25 02:18:31,20.05,1148374505062
10,Kelseyland,63,Urban,2016-01-25 08:47:09,9.29,213692794373
11,Kelseyland,63,Urban,2016-11-10 01:57:14,20.58,3395682132130
12,Kelseyland,63,Urban,2016-08-15 11:55:02,27.45,8456148871668
13,Kelseyland,63,Urban,2016-08-01 10:51:49,33.51,6610565660737
14,Kelseyland,63,Urban,2016-04-13 12:07:08,6.56,8101498434215
15,Kelseyland,63,Urban,2016-01-12 22:51:21,20.19,3054122642867
16,Kelseyland,63,Urban,2016-05-31 01:05:31,35.22,5946467060438
17,Kelseyland,63,Urban,2016-07-13 16:53:07,10.31,2180910323678
18,Kelseyland,63,Urban,2016-01-07 07:15:41,11.45,600800386573
19,Kelseyland,63,Urban,2016-04-09 13:17:27,27.85,5748868894243
20,Kelseyland,63,Urban,2016-06-30 01:59:04,8.27,4384089549855
21,Kelseyland,63,Urban,2016-04-20 05:36:59,31.67,2865704421982
22,Kelseyland,63,Urban,2016-05-02 05:55:28,40.92,2769007541388
23,Kelseyland,63,Urban,2016-06-22 06:54:57,12.58,6629798205387
24,Kelseyland,63,Urban,2016-06-18 06:03:03,16.77,7223504701591
25,Kelseyland,63,Urban,2016-01-09 20:28:56,27.21,831362906446
26,Kelseyland,63,Urban,2016-07-22 19:28:21,35.71,1234880130185
27,Kelseyland,63,Urban,2016-11-26 02:34:57,15.49,5187807155760
28,Nguyenbury,8,Urban,2016-07-09 04:42:44,6.28,1543057793673
29,Nguyenbury,8,Urban,2016-11-08 19:22:04,19.49,1702803950740
...,...,...,...,...,...,...
2377,East Leslie,9,Rural,2016-04-13 04:30:56,40.47,7075058703398
2378,East Leslie,9,Rural,2016-04-26 02:34:30,45.80,9402873395510
2379,East Leslie,9,Rural,2016-04-05 18:53:16,44.78,6113138249150
2380,East Leslie,9,Rural,2016-11-13 10:21:10,15.71,7275986542384
2381,East Leslie,9,Rural,2016-03-06 06:10:40,51.32,6841691147797
2382,East Leslie,9,Rural,2016-03-04 10:18:03,13.43,8814831098684
2383,East Leslie,9,Rural,2016-11-28 09:09:15,37.76,804829686137
2384,East Leslie,9,Rural,2016-09-08 19:19:38,30.59,8211833105097
2385,East Leslie,9,Rural,2016-03-02 22:09:34,36.61,5500269118478
2386,East Leslie,9,Rural,2016-06-22 07:45:30,34.54,684950063164
2387,Hernandezshire,10,Rural,2016-02-20 08:17:32,58.95,3176534714830
2388,Hernandezshire,10,Rural,2016-06-26 20:11:50,28.78,6382848462030
2389,Hernandezshire,10,Rural,2016-01-24 00:21:35,30.32,7342649945759
2390,Hernandezshire,10,Rural,2016-03-05 10:40:16,23.35,7443355895137
2391,Hernandezshire,10,Rural,2016-04-11 04:44:50,10.41,9823290002445
2392,Hernandezshire,10,Rural,2016-06-26 11:16:28,26.29,304182959218
2393,Hernandezshire,10,Rural,2016-11-25 20:34:14,38.45,2898512024847
2394,Hernandezshire,10,Rural,2016-11-20 17:32:37,26.79,3095402154397
2395,Hernandezshire,10,Rural,2016-02-24 17:30:44,44.68,6389115653382
2396,Horneland,8,Rural,2016-07-19 10:07:33,12.63,8214498891817
2397,Horneland,8,Rural,2016-03-22 21:22:20,31.53,1797785685674
2398,Horneland,8,Rural,2016-01-26 09:38:17,21.73,5665544449606
2399,Horneland,8,Rural,2016-03-25 02:05:42,20.04,5729327140644
2400,West Kevintown,5,Rural,2016-11-27 20:12:58,12.92,6460741616450
2401,West Kevintown,5,Rural,2016-02-19 01:42:58,11.15,8622534016726
2402,West Kevintown,5,Rural,2016-03-11 09:03:43,42.13,4568909568268
2403,West Kevintown,5,Rural,2016-06-25 08:04:12,24.53,8188407925972
2404,West Kevintown,5,Rural,2016-07-24 13:41:23,11.78,2001192693573
2405,West Kevintown,5,Rural,2016-06-15 19:53:16,13.50,9577921579881
2406,West Kevintown,5,Rural,2016-02-10 00:50:04,34.69,9595491362610

In [21]:
rides = [0,5,10,15,20,25,30,35,40]
type = ["Urban", "Suburban", "Rural"]
color = ["orange", "blue", "yellow"]

plt.scatter(numpy.arange(rides, type, color="orange", label="Urban"))
plt.scatter(numpy.arange(rides, type, color="blue", label="Suburban"))
plt.scatter(numpy.arange(rides, type, color="yellow", label="Rural"))

plt.legend(loc="best")

plt.title("Pyber Ride Sharing Data")
plt.xlabel("Total Number of Rides(Per City)")
plt.ylabel("Average Fare")

plt.axis("equal")
plt.show()

TypeError: 'color' is an invalid keyword argument for this function

In [24]:
#Pie Label
labels = ["Rural", "Urban","Suburban"]

#Pie value
size = [185, 172, 100 , 110]

#pie Color
colors = ["pink", "yellow", "blue"]

explode = (0.1,0,0,0)

In [26]:
plt.pie(size, explode=explode, labels=labels, colors=colors,
       autopct="%1.1f%%", shadow=True, startangle=140)
plt.axis("equal")
plt.show()

ValueError: 'label' must be of length 'x'

In [27]:
for row in combined_city_df:
    city.append(row[0])
    type.append(row[1])
    fare.append(row[2])

plt.pie(fare, labels=type)

plt.legend(loc="best")

plt.title("% of Total Fares by City Type")
plt.show()

NameError: name 'city' is not defined

In [28]:
for row in combined_city_df:
    city.append(row[0])
    type.append(row[1])
    ride_id.append(row[2])

plt.pie(ride_id, labels=type)

plt.legend(loc="best")

plt.title("% of Total Rides by City Type")
plt.show()

NameError: name 'driver_count' is not defined

In [ ]:
for row in combined_city_df:
    driver_count.append(row[0])
    type.append(row[1])
    ride_id.append(row[2])

plt.pie(driver_count, labels=type)

plt.legend(loc="best")

plt.title("% of Total Drivers by City Type")
plt.show()